config/routes.rb
Rails.application.routes.draw do
  resources :candidatos
  root 'candidatos#index'

end

app/models/candidato.rb
class Candidato < ActiveRecord::Base
end

app/controllers/OAuth2.rb
require 'open-uri'

kittens = open('http://placekitten.com/')
response_status = kittens.status
response_body = kittens.read[559, 441]

puts response_status
puts response_body

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :set_candidato, only: [:show, :edit, :update, :destroy]

  # GET /candidatos
  # GET /candidatos.json
  def index
    @candidatos = Candidato.all
  end

  # GET /candidatos/1
  # GET /candidatos/1.json
  def show
  end

  # GET /candidatos/new
  def new
    @candidato = Candidato.new
  end

  # GET /candidatos/1/edit
  def edit
  end

  # POST /candidatos
  # POST /candidatos.json
  def create
    @candidato = Candidato.new(candidato_params)

    respond_to do |format|
      if @candidato.save
        format.html { redirect_to @candidato, notice: 'Candidato was successfully created.' }
        format.json { render :show, status: :created, location: @candidato }
      else
        format.html { render :new }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /candidatos/1
  # PATCH/PUT /candidatos/1.json
  def update
    respond_to do |format|
      if @candidato.update(candidato_params)
        format.html { redirect_to @candidato, notice: 'Candidato was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidato }
      else
        format.html { render :edit }
        format.json { render json: @candidato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /candidatos/1
  # DELETE /candidatos/1.json
  def destroy
    @candidato.destroy
    respond_to do |format|
      format.html { redirect_to candidatos_url, notice: 'Candidato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidato
      @candidato = Candidato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def candidato_params
      params.require(:candidato).permit(:nombre, :rut, :email, :telefono_movil, :tetefono_fijo, :direccion, :ciudad_pais_nacimiento, :fecha_nacimiento, :otro_contacto, :situacion_laboral, :anos_experiencia, :expectativa_renta, :tipo_contrato, :fecha_disponibilidad, :tipo_asignacion, :asignado_empresa, :renta, :fecha_inicio_asignacion, :fecha_fin_asignacion, :persona_contacto, :comentario, :empresa, :cargo, :fecha_inicio_experiencia, :fecha_fin_experiencia, :ciudad_pais_empresa, :descripcion, :titulo, :universidad, :ciudad_pais_universidad, :fecha_grado, :certificaciones, :competencias, :idiomas, :intereses, :referencias)
    end
end

app/controllers/kitts.rb
require 'open-uri'

kittens = open('http://placekitten.com/200/300')

f = File.open('kittens.jpg', 'w')
kittens.each do |kitten|
  f.write(kitten)
end

f.close

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidatos_helper.rb
module CandidatosHelper
end

app/views/candidatos/_form.html.erb
<%= form_for(@candidato) do |f| %>
  <% if @candidato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@candidato.errors.count, "error") %> prohibited this candidato from being saved:</h2>

      <ul>
      <% @candidato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="newspaper">
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :rut %><br>
    <%= f.text_field :rut %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telefono_movil %><br>
    <%= f.text_field :telefono_movil %>
  </div>
  <div class="field">
    <%= f.label :tetefono_fijo %><br>
    <%= f.text_field :tetefono_fijo %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :ciudad_pais_nacimiento %><br>
    <%= f.text_field :ciudad_pais_nacimiento %>
  </div>
  <div class="field">
    <%= f.label :fecha_nacimiento %><br>
    <%= f.date_select :fecha_nacimiento %>
  </div>
  <div class="field">
    <%= f.label :otro_contacto %><br>
    <%= f.text_field :otro_contacto %>
  </div>
  <div class="field">
    <%= f.label :situacion_laboral %><br>
    <%= f.text_field :situacion_laboral %>
  </div>
  <div class="field">
    <%= f.label :anos_experiencia %><br>
    <%= f.text_field :anos_experiencia %>
  </div>
  <div class="field">
    <%= f.label :expectativa_renta %><br>
    <%= f.text_field :expectativa_renta %>
  </div>
  <div class="field">
    <%= f.label :tipo_contrato %><br>
    <%= f.text_field :tipo_contrato %>
  </div>
  <div class="field">
    <%= f.label :fecha_disponibilidad %><br>
    <%= f.text_field :fecha_disponibilidad %>
  </div>
  <div class="field">
    <%= f.label :tipo_asignacion %><br>
    <%= f.text_field :tipo_asignacion %>
  </div>
  <div class="field">
    <%= f.label :asignado_empresa %><br>
    <%= f.text_field :asignado_empresa %>
  </div>
  <div class="field">
    <%= f.label :renta %><br>
    <%= f.text_field :renta %>
  </div>
  <div class="field">
    <%= f.label :fecha_inicio_asignacion %><br>
    <%= f.date_select :fecha_inicio_asignacion %>
  </div>
  <div class="field">
    <%= f.label :fecha_fin_asignacion %><br>
    <%= f.date_select :fecha_fin_asignacion %>
  </div>
  <div class="field">
    <%= f.label :persona_contacto %><br>
    <%= f.text_field :persona_contacto %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br>
    <%= f.text_field :comentario %>
  </div>
  <div class="field">
    <%= f.label :empresa %><br>
    <%= f.text_field :empresa %>
  </div>
  <div class="field">
    <%= f.label :cargo %><br>
    <%= f.text_field :cargo %>
  </div>
  <div class="field">
    <%= f.label :fecha_inicio_experiencia %><br>
    <%= f.date_select :fecha_inicio_experiencia %>
  </div>
  <div class="field">
    <%= f.label :fecha_fin_experiencia %><br>
    <%= f.date_select :fecha_fin_experiencia %>
  </div>
  <div class="field">
    <%= f.label :ciudad_pais_empresa %><br>
    <%= f.text_field :ciudad_pais_empresa %>
  </div>
  <div class="field">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion %>
  </div>
  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :universidad %><br>
    <%= f.text_field :universidad %>
  </div>
  <div class="field">
    <%= f.label :ciudad_pais_universidad %><br>
    <%= f.text_field :ciudad_pais_universidad %>
  </div>
  <div class="field">
    <%= f.label :fecha_grado %><br>
    <%= f.date_select :fecha_grado %>
  </div>
  <div class="field">
    <%= f.label :certificaciones %><br>
    <%= f.text_field :certificaciones %>
  </div>
  <div class="field">
    <%= f.label :competencias %><br>
    <%= f.text_field :competencias %>
  </div>
  <div class="field">
    <%= f.label :idiomas %><br>
    <%= f.text_field :idiomas %>
  </div>
  <div class="field">
    <%= f.label :intereses %><br>
    <%= f.text_field :intereses %>
  </div>
  <div class="field">
    <%= f.label :referencias %><br>
    <%= f.text_field :referencias %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
</div>  
<% end %>

app/views/candidatos/edit.html.erb
<div class="container">

	<div class="row">

    <div class="col-md-3">
          
        <p class="lead">Editar Candidato</p>
        <!-- <h1>Editing Candidato</h1> -->

        <%= render 'form' %>
        
        <%= link_to 'Show', @candidato %> |
        <%= link_to 'Back', candidatos_path %>

     </div>
     
	</div>

</div>

app/views/candidatos/index.html.erb
<div class="container">

	<div class="row">

    <div class="col-md-3">
          
          <p class="lead">Listado de Candidatos</p>

          <table class="table table-bordered table-striped">
            <thead>
              <tr>
                <th>Nombre</th>
        <!--    <th>Rut</th>    -->
                <th>Email</th>
                <th>Telefono movil</th>
        <!--    <th>Tetefono fijo</th>
                <th>Direccion</th>
                <th>Ciudad pais nacimiento</th>
                <th>Fecha nacimiento</th>
                <th>Otro contacto</th>    -->
                <th>Situacion laboral</th>
        <!--    <th>Anos experiencia</th>
                <th>Expectativa renta</th>
                <th>Tipo contrato</th>
                <th>Fecha disponibilidad</th>
                <th>Tipo asignacion</th>
                <th>Asignado empresa</th>
                <th>Renta</th>
                <th>Fecha inicio asignacion</th>
                <th>Fecha fin asignacion</th>
                <th>Persona contacto</th>
                <th>Comentario</th>
                <th>Empresa</th>
                <th>Cargo</th>
                <th>Fecha inicio experiencia</th>
                <th>Fecha fin experiencia</th>
                <th>Ciudad pais empresa</th>
                <th>Descripcion</th>    -->
                <th>Titulo</th>
        <!--    <th>Universidad</th>
                <th>Ciudad pais universidad</th>
                <th>Fecha grado</th>
                <th>Certificaciones</th>
                <th>Competencias</th>
                <th>Idiomas</th>
                <th>Intereses</th>
                <th>Referencias</th>    -->
                <th colspan="3"></th>
              </tr>
            </thead>
          
            <tbody>
              <% @candidatos.each do |candidato| %>
                <tr>
                  <td><%= candidato.nombre %></td>
          <!--    <td><%= candidato.rut %></td>    -->
                  <td><%= candidato.email %></td>
                  <td><%= candidato.telefono_movil %></td>
          <!--    <td><%= candidato.tetefono_fijo %></td>
                  <td><%= candidato.direccion %></td>
                  <td><%= candidato.ciudad_pais_nacimiento %></td>
                  <td><%= candidato.fecha_nacimiento %></td>
                  <td><%= candidato.otro_contacto %></td>    -->
                  <td><%= candidato.situacion_laboral %></td>
          <!--    <td><%= candidato.anos_experiencia %></td>
                  <td><%= candidato.expectativa_renta %></td>
                  <td><%= candidato.tipo_contrato %></td>
                  <td><%= candidato.fecha_disponibilidad %></td>
                  <td><%= candidato.tipo_asignacion %></td>
                  <td><%= candidato.asignado_empresa %></td>
                  <td><%= candidato.renta %></td>
                  <td><%= candidato.fecha_inicio_asignacion %></td>
                  <td><%= candidato.fecha_fin_asignacion %></td>
                  <td><%= candidato.persona_contacto %></td>
                  <td><%= candidato.comentario %></td>
                  <td><%= candidato.empresa %></td>
                  <td><%= candidato.cargo %></td>
                  <td><%= candidato.fecha_inicio_experiencia %></td>
                  <td><%= candidato.fecha_fin_experiencia %></td>
                  <td><%= candidato.ciudad_pais_empresa %></td>
                  <td><%= candidato.descripcion %></td>    -->
                  <td><%= candidato.titulo %></td>
          <!--    <td><%= candidato.universidad %></td>
                  <td><%= candidato.ciudad_pais_universidad %></td>
                  <td><%= candidato.fecha_grado %></td>
                  <td><%= candidato.certificaciones %></td>
                  <td><%= candidato.competencias %></td>
                  <td><%= candidato.idiomas %></td>
                  <td><%= candidato.intereses %></td>
                  <td><%= candidato.referencias %></td>    -->
                  <td><%= link_to 'Ver', candidato %></td>
                  <td><%= link_to 'Editar', edit_candidato_path(candidato) %></td>
                  <td><%= link_to 'Borrar', candidato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          
          <br>
          
          <%= link_to 'Nuevo Candidato', new_candidato_path %>
      </div>
	</div>

</div>

app/views/candidatos/new.html.erb
<div class="container">

	<div class="row">

    <div class="col-md-3">
          
        <p class="lead">Nuevo Candidato</p>
        <!-- <h1>New Candidato</h1> -->
        
        <%= render 'form' %>
        
        <%= link_to 'Back', candidatos_path %>
        
        
     </div>
     
	</div>

</div>

app/views/candidatos/show.html.erb
<div class="container">

	<div class="row">

    <div class="col-md-3">
          
        <p class="lead">Candidato</p>
        
        <p id="notice"><%= notice %></p>
        
        <p>
          <strong>Nombre:</strong>
          <%= @candidato.nombre %>
        </p>
        
        <p>
          <strong>Rut:</strong>
          <%= @candidato.rut %>
        </p>
        
        <p>
          <strong>Email:</strong>
          <%= @candidato.email %>
        </p>
        
        <p>
          <strong>Telefono movil:</strong>
          <%= @candidato.telefono_movil %>
        </p>
        
        <p>
          <strong>Tetefono fijo:</strong>
          <%= @candidato.tetefono_fijo %>
        </p>
        
        <p>
          <strong>Direccion:</strong>
          <%= @candidato.direccion %>
        </p>
        
        <p>
          <strong>Ciudad pais nacimiento:</strong>
          <%= @candidato.ciudad_pais_nacimiento %>
        </p>
        
        <p>
          <strong>Fecha nacimiento:</strong>
          <%= @candidato.fecha_nacimiento %>
        </p>
        
        <p>
          <strong>Otro contacto:</strong>
          <%= @candidato.otro_contacto %>
        </p>
        
        <p>
          <strong>Situacion laboral:</strong>
          <%= @candidato.situacion_laboral %>
        </p>
        
        <p>
          <strong>Anos experiencia:</strong>
          <%= @candidato.anos_experiencia %>
        </p>
        
        <p>
          <strong>Expectativa renta:</strong>
          <%= @candidato.expectativa_renta %>
        </p>
        
        <p>
          <strong>Tipo contrato:</strong>
          <%= @candidato.tipo_contrato %>
        </p>
        
        <p>
          <strong>Fecha disponibilidad:</strong>
          <%= @candidato.fecha_disponibilidad %>
        </p>
        
        <p>
          <strong>Tipo asignacion:</strong>
          <%= @candidato.tipo_asignacion %>
        </p>
        
        <p>
          <strong>Asignado empresa:</strong>
          <%= @candidato.asignado_empresa %>
        </p>
        
        <p>
          <strong>Renta:</strong>
          <%= @candidato.renta %>
        </p>
        
        <p>
          <strong>Fecha inicio asignacion:</strong>
          <%= @candidato.fecha_inicio_asignacion %>
        </p>
        
        <p>
          <strong>Fecha fin asignacion:</strong>
          <%= @candidato.fecha_fin_asignacion %>
        </p>
        
        <p>
          <strong>Persona contacto:</strong>
          <%= @candidato.persona_contacto %>
        </p>
        
        <p>
          <strong>Comentario:</strong>
          <%= @candidato.comentario %>
        </p>
        
        <p>
          <strong>Empresa:</strong>
          <%= @candidato.empresa %>
        </p>
        
        <p>
          <strong>Cargo:</strong>
          <%= @candidato.cargo %>
        </p>
        
        <p>
          <strong>Fecha inicio experiencia:</strong>
          <%= @candidato.fecha_inicio_experiencia %>
        </p>
        
        <p>
          <strong>Fecha fin experiencia:</strong>
          <%= @candidato.fecha_fin_experiencia %>
        </p>
        
        <p>
          <strong>Ciudad pais empresa:</strong>
          <%= @candidato.ciudad_pais_empresa %>
        </p>
        
        <p>
          <strong>Descripcion:</strong>
          <%= @candidato.descripcion %>
        </p>
        
        <p>
          <strong>Titulo:</strong>
          <%= @candidato.titulo %>
        </p>
        
        <p>
          <strong>Universidad:</strong>
          <%= @candidato.universidad %>
        </p>
        
        <p>
          <strong>Ciudad pais universidad:</strong>
          <%= @candidato.ciudad_pais_universidad %>
        </p>
        
        <p>
          <strong>Fecha grado:</strong>
          <%= @candidato.fecha_grado %>
        </p>
        
        <p>
          <strong>Certificaciones:</strong>
          <%= @candidato.certificaciones %>
        </p>
        
        <p>
          <strong>Competencias:</strong>
          <%= @candidato.competencias %>
        </p>
        
        <p>
          <strong>Idiomas:</strong>
          <%= @candidato.idiomas %>
        </p>
        
        <p>
          <strong>Intereses:</strong>
          <%= @candidato.intereses %>
        </p>
        
        <p>
          <strong>Referencias:</strong>
          <%= @candidato.referencias %>
        </p>
        
        <%= link_to 'Edit', edit_candidato_path(@candidato) %> |
        <%= link_to 'Back', candidatos_path %>
      </div>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HrSystemvanCl</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<!-- AM navbar-->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Systemvan</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contacto</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
<!-- AM navbar-->
<%= yield %>

<!-- AM Footer-->
<div class="container">
        <!-- Footer -->
        <footer>
           <hr>
            <div class="col-lg-12">
                <p>Desarrollado por © monpeco@gmail.com / 2016</p>
            </div>
        </footer>
</div>
<!-- AM Footer-->

</body>
</html>